all:
  children: 
    WindowsMachine:
      hosts:
        192.168.88.254:
    CentosMachine1:
      hosts:
        192.168.99.100:

    WindowsMachines:
      children:
        WindowsMachine:

    CentosMachines:
      children:
        CentosMachine1:

