---
- name: test download from Nexus
  hosts: WindowsMachines

  tasks:

  - name: Ping servers
    win_ping:

  - name: download tomcat from Nexus with Auth
    win_get_url:
      url:  http://192.168.88.254:8081/repository/distr/test/apache-tomcat-9.0.37-windows-x86.zip
      dest: C:\tempForNexus\apache-tomcat-9.0.37-windows-x86.zip
      url_username: admin
      url_password: admin123

