---
- name: test ping win Machines
  hosts: WindowsMachines

  tasks:

  - name: Ping servers
    win_ping:

  - name: Install JDK8 on Windows Machine
    win_package:
      path: C:\\temp\\jdk-8u261-windows-i586.exe
      product_id: jdk-8u261
      arguments:
      - /s
      - /quiet
      state: present
      log_path: D:\temp\jdk8.log
